use_frameworks!

platform :ios, '9.0'

target 'Uncle_button_Example' do
  pod 'Uncle_button', :path => '../'

  target 'Uncle_button_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
